### ISSUE TITLE
Deep Learning 101

### ISSUE THREAD

**Issue by shubhi-sareen** [WTM-NewDelhi/Proposals#3]
**Abstract**

I will be discussing the basics of Deep Learning and how it affects our lives, and how it can impact all walks of life. 

**About**
1. Why Deep Learning?
    * How deep learning came into existence?
    * The impact it has created
2. 4 Types of Neural Networks everyone should know
    * Artificial Neural Networks
    * Convolutional Neural Networks
    * Recurrent Neural Networks
    * Generative Adversarial Networks
3. Coding ANN from Scratch

**Format**

Talk Session + CodeLab

**Pre-requisites**

- Enthusiasm 

**Expected duration**

90 minutes

**Level**

Beginner

**Previous Experience/Sample ppt**

All my talks can be found at this [Github Repository](https://github.com/shubhi-sareen/Talks)
For testimonials and my experience as a speaker: [Takeaways from Teaching](https://medium.com/@ShubhiSareen/takeaways-from-teaching-ef5b432ae662)

**Speaker Bio**

I am a 3rd Year Computer Engineering Undergraduate at Delhi Technological University. A former Google Intern and a Machine Learning enthusiast, I am passionate about technology and have won various Hackathons including Smart India Hackathon and Clean Air Asia Hackathon. In times, when we have an access to enormous amount of data in the form of words, texts, and images, I want to explore more on how this can be used to make meaningful interpretations about the world around us; and therefore, am always seeking new opportunities that will hone my skills, which will, in turn, enable me to make a difference in the field of technology, and as a result, the life of the people.

**LinkedIn/Twitter Profile**

[Linkedin](https://www.linkedin.com/in/shubhi-sareen/)
[Twitter](https://twitter.com/shubhi_sareen)
 
**How will it help developers/students**

It will introduce attendees to Deep Learning and various kinds of Neural Networks and their applications. The session aims to provide an intuitive feeling about Neural Networks and how they work. The attendees can further apply this knowledge to various real-life problem statements.

**Comment by anubhakushwaha** [comment]
Closing, talk addressed at IWD-18, [here](https://github.com/WTM-NewDelhi/IWD-18Slides)
