### ISSUE TITLE
Freelancing, Self Branding & Money Minting

### ISSUE THREAD

**Issue by punitweb** [WTM-NewDelhi/Proposals#8]
**Abstract**
I will be explaining and sharing my experiences as a freelancer and how to make more money sitting at home ( as a designer and developer ). Also, I will be sharing the keys to self branding and how to use the flaws of the industry to one's advantage.

**About**
- Freelancing
   - What is freelancing and why it's a great alternative for a 9-5 job.
   - How to start freelancing and get good at it.
   - What NOT to do as a freelancer.
- Self Branding
   - What is self branding and why it's absolutely necessary.
   - How to set up your own brand and make it flourish.
 - Money Minting
   - How to make more money as a designer or developer.
   - How and Why to never undervalue yourself. How to measure the value of one's work.
   - How to always have more than one source of income.

**Format**

- Talk Session
- Experience Sharing

**Pre-requisites**

- High and Positive energy, that's it. ( Also,  I'm open to flash photography ;) )

**Expected duration**

30 - 40 Min

**Level**

Beginner ( All levels will benefit )

**Previous Experience/Sample ppt**

Google I/O 2017 - [LINK](https://docs.google.com/presentation/d/1NcMTH3IHB3Lg48Da37Snw15it6_BelEUgd5zVly6fOE/edit?usp=sharing)
GDG Devfest 2017 - [LINK](https://docs.google.com/presentation/d/1yKcFqzJv48-VV9xWWK9p1KDmAPDz_vc3TZFQEWOZh54/edit?usp=sharing)

**Speaker Bio**

I am Punit Chawla, also known as Punitweb. I am a UX/UI Designer from Delhi working with multiple startups to help them grow and consult their designing processes.

**LinkedIn/Twitter Profile**

[Linkedin](https://www.linkedin.com/in/punitweb)
[Twitter](https://twitter.com/punitweb)
[Facebook](https://www.facebook.com/punitweb)

**How will it help developers/students**
Developers, designers / students are often making the wrong decisions when it comes to freelancing, self branding and making money. I understand, since I've also been there, but I've learned from my mistakes. I want to pass all that I've learned about the industry and how I've battled through to get actual clients, since talent has always been overrated.

**Comment by anubhakushwaha** [comment]
@punitweb Can you please provide me your email-id ?

**Comment by punitweb** [comment]
punitweb@pm.me @anubhakushwaha

**Comment by anubhakushwaha** [comment]
Closing, talk addressed at IWD-18, [here](https://github.com/WTM-NewDelhi/IWD-18Slides)
